apiVersion: v1
kind: Service
metadata:
  name: emoji-api
  labels:
    app: emoji-api
    version: "1"
spec:
  ports:
  - name: http-traffic
    targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: emoji-api
    version: "1"